services:
  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    environment:
      - DEBUG=1
    restart: always
    networks:
      - mynetwork 
    command: >
      sh -c "python manage.py migrate &&
             python manage.py shell < helpers/create_superuser.py &&
             python manage.py runserver 0.0.0.0:8000"


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    depends_on:
      - django
    restart: always
    environment:
      - VITE_API_BASE_URL=http://django:8000 # Tell frontend where to find the backend
    networks:
      - mynetwork  # Add this network

networks:
  mynetwork:
